### ISSUE TITLE
Outdated information makes the Action Item impossible to follow

### ISSUE THREAD

**Issue by Starving-Rtist** [learn-co-curriculum/macos-env-flatiron-student-portal#5]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4706/assignments/130717?module_item_id=270493

## What should be changed?

Under Action Item, the instruction tells us to go to the Portal to set up "learn-co", however the Portal has this message "Flatiron School is no longer offering course content on Learn.co". The actual place we should head to is "Base".

## Additional context

The README.md file in Github for this assignment actually has the correct links and locations.

**Comment by ihollander** [comment]
Hi @Starving-Rtist - thanks for flagging this issue! We recently updated the GitHub repository that is used for this lesson in Canvas to a newer version with the updated instructions for incoming students: https://github.com/learn-co-curriculum/phase-0-configuring-the-flatiron-student-portal

Your Canvas course didn't receive this update, but I just went ahead and manually changed your course's Canvas page to reflect the new instructions: https://learning.flatironschool.com/courses/4706/assignments/130717?module_item_id=270493
